# Generated by Django 4.0.3 on 2022-06-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icone')),
                ('badge_color', models.CharField(max_length=10, verbose_name='Couleur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('slug', models.SlugField()),
                ('cover_image', models.ImageField(upload_to='', verbose_name='Image de couverture')),
                ('summary', models.CharField(max_length=120, verbose_name='Resumé')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=True, verbose_name='Publié')),
                ('visibled', models.BooleanField(default=True, verbose_name='Visible')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.postcategory')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.posttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
