# Generated by Django 4.0.3 on 2022-06-15 19:06

import blog.models
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0002_alter_post_slug_alter_postcategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(upload_to=blog.models.post_images, verbose_name='Image de couverture'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='badge_color',
            field=models.CharField(blank=True, max_length=10, verbose_name='Couleur'),
        ),
    ]
