# Generated by Django 4.0.3 on 2022-06-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userinvite_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvite',
            name='referer_code',
        ),
        migrations.RemoveField(
            model_name='userinvite',
            name='register_link_openned',
        ),
        migrations.AddField(
            model_name='userinvite',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nom complet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinvite',
            name='referral_code',
            field=models.UUIDField(blank=True, default='70571f10-8c9f-4b96-8f14-4363d9ce5eca'),
        ),
        migrations.AddField(
            model_name='userinvite',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Vérifié'),
        ),
        migrations.AddField(
            model_name='userinvite',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse email'),
        ),
    ]
