# Generated by Django 4.0.3 on 2022-03-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='fetched',
            field=models.BooleanField(default=False),
        ),
    ]
