# Generated by Django 4.0.3 on 2022-06-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_fetched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotetag',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
